parameters:
  remove_stylesheets: []
  remove_scripts:
    - "jquery"
  stylesheets:
    - { name: "google", source: "https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i", requires: [], version: false, media: "all" }
    - { name: "sapling", source: "%theme_uri%/web/stylesheets/app.css", requires: ["google"], version: false, media: "all" }
  scripts:
    - { name: "jquery", source: "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js", requires: [], version: "3.1.1", footer: true }
    - { name: "sapling", source: "%theme_uri%/web/jsmin/app.min.js", requires: ['jquery'], version: false, footer: true }
  image_sizes:
    - { name: "hero", width: 900, height: 300, crop: true, add_filter: true, filter_name: "Hero" }
  remove_theme_supports: []
  theme_supports:
    - "post-thumbnails"
    - "html5"
  remove_menus: []
  menus:
    primary: "Primary Menu"
    footer: "Footer Menu"
  post_types:
    publication:
      public: true
      has_archive: true
      labels: {name: "Publications", singular_name: "Publication"}
      menu_position: 6
      menu_icon: "dashicons-portfolio"
      supports: ["title", "editor", "thumbnail"]
    sheet_music:
      public: true
      has_archive: true
      labels: {name: "Sheet Music", singular_name: "Sheet Music"}
      menu_position: 6
      menu_icon: "dashicons-playlist-audio"
      supports: ["title", "editor", "thumbnail"]
    recording:
      public: true
      has_archive: true
      labels: {name: "Recordings", singular_name: "Recording"}
      menu_position: 6
      menu_icon: "dashicons-format-audio"
      supports: ["title", "editor"]
  remove_post_type_support: []
  post_type_support: []
  remove_sidebars: []
  sidebars: []
  remove_theme_mods: []
  theme_mods: []
  remove_oembed_provider: []